pull_request_title: Update translations from Crowdin
append_commit_message: 
commit_message: Updated %language% translations.
files:
  - source: /resources/assets/fetchr/lang/en_us.json
    translation: /resources/assets/fetchr/lang/%locale_with_underscore%.json
  - source: /resources/assets/minecraft/lang/en_us.json
    translation: /resources/assets/minecraft/lang/%locale_with_underscore%.json
