files:
  - source: /assets/bingo/lang/en_us.json
    translation: /assets/bingo/lang/%locale_with_underscore%.json
  - source: /assets/minecraft/lang/en_us.json
    translation: /assets/minecraft/lang/%locale_with_underscore%.json
