data modify storage fetchr:registries categories append value {id: "fetchr:basalt", name: '{"translate": "fetchr.category.basalt"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:bastion", name: '{"translate": "fetchr.category.bastion"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:blaze", name: '{"translate": "fetchr.category.blaze"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:crimson", name: '{"translate": "fetchr.category.crimson"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:diamond", name: '{"translate": "fetchr.category.diamond"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:diamond_tool", name: '{"translate": "fetchr.category.diamond_tool"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:enderman", name: '{"translate": "fetchr.category.enderman"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:flint", name: '{"translate": "fetchr.category.flint"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:fortress", name: '{"translate": "fetchr.category.fortress"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:ghast", name: '{"translate": "fetchr.category.ghast"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:gold", name: '{"translate": "fetchr.category.gold"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:golden_armor", name: '{"translate": "fetchr.category.golden_armor"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:golden_tool", name: '{"translate": "fetchr.category.golden_tool"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:hoglin", name: '{"translate": "fetchr.category.hoglin"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:iron", name: '{"translate": "fetchr.category.iron"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:light", name: '{"translate": "fetchr.category.light"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:magma_cream", name: '{"translate": "fetchr.category.magma_cream"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:misc", name: '{"translate": "fetchr.category.misc"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:mushroom", name: '{"translate": "fetchr.category.mushroom"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:nether_wart", name: '{"translate": "fetchr.category.nether_wart"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:netherite", name: '{"translate": "fetchr.category.netherite"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:obsidian", name: '{"translate": "fetchr.category.obsidian"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:ore", name: '{"translate": "fetchr.category.ore"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:piglin", name: '{"translate": "fetchr.category.piglin"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:potion", name: '{"translate": "fetchr.category.potion"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:quartz", name: '{"translate": "fetchr.category.quartz"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:skeleton", name: '{"translate": "fetchr.category.skeleton"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:soul_block", name: '{"translate": "fetchr.category.soul_block"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:soul_light", name: '{"translate": "fetchr.category.soul_light"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:treasure", name: '{"translate": "fetchr.category.treasure"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:warped", name: '{"translate": "fetchr.category.warped"}', tags: ["fetchr:default"]}
data modify storage fetchr:registries categories append value {id: "fetchr:wither", name: '{"translate": "fetchr.category.wither"}', tags: ["fetchr:default"]}
