## 0100: ancient_debris
data modify storage fetchr:registries items append value {id: "fetchr:ancient_debris", item: {id: "minecraft:ancient_debris"}, textComponent: '{"translate": "block.minecraft.ancient_debris", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:ancient_debris"}}}', icon: '"\\u0100"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:ancient_debris 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:ancient_debris 1", categories: ["fetchr:netherite"]}
## 0101: bone_block
data modify storage fetchr:registries items append value {id: "fetchr:bone_block", item: {id: "minecraft:bone_block"}, textComponent: '{"translate": "block.minecraft.bone_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:bone_block"}}}', icon: '"\\u0101"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:bone_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:bone_block 1", categories: ["fetchr:soul_block"]}
## 0102: chiseled_nether_bricks
data modify storage fetchr:registries items append value {id: "fetchr:chiseled_nether_bricks", item: {id: "minecraft:chiseled_nether_bricks"}, textComponent: '{"translate": "block.minecraft.chiseled_nether_bricks", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:chiseled_nether_bricks"}}}', icon: '"\\u0102"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:chiseled_nether_bricks 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:chiseled_nether_bricks 1", categories: ["fetchr:fortress"]}
## 0103: chiseled_polished_blackstone
data modify storage fetchr:registries items append value {id: "fetchr:chiseled_polished_blackstone", item: {id: "minecraft:chiseled_polished_blackstone"}, textComponent: '{"translate": "block.minecraft.chiseled_polished_blackstone", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:chiseled_polished_blackstone"}}}', icon: '"\\u0103"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:chiseled_polished_blackstone 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:chiseled_polished_blackstone 1", categories: ["fetchr:bastion"]}
## 0104: chiseled_quartz_block
data modify storage fetchr:registries items append value {id: "fetchr:chiseled_quartz_block", item: {id: "minecraft:chiseled_quartz_block"}, textComponent: '{"translate": "block.minecraft.chiseled_quartz_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:chiseled_quartz_block"}}}', icon: '"\\u0104"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:chiseled_quartz_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:chiseled_quartz_block 1", categories: ["fetchr:quartz"]}
## 0105: cracked_nether_bricks
data modify storage fetchr:registries items append value {id: "fetchr:cracked_nether_bricks", item: {id: "minecraft:cracked_nether_bricks"}, textComponent: '{"translate": "block.minecraft.cracked_nether_bricks", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:cracked_nether_bricks"}}}', icon: '"\\u0105"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:cracked_nether_bricks 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:cracked_nether_bricks 1", categories: ["fetchr:fortress"]}
## 0106: cracked_polished_blackstone_bricks
data modify storage fetchr:registries items append value {id: "fetchr:cracked_polished_blackstone_bricks", item: {id: "minecraft:cracked_polished_blackstone_bricks"}, textComponent: '{"translate": "block.minecraft.cracked_polished_blackstone_bricks", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:cracked_polished_blackstone_bricks"}}}', icon: '"\\u0106"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:cracked_polished_blackstone_bricks 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:cracked_polished_blackstone_bricks 1", categories: ["fetchr:bastion"]}
## 0107: crimson_fence_gate
data modify storage fetchr:registries items append value {id: "fetchr:crimson_fence_gate", item: {id: "minecraft:crimson_fence_gate"}, textComponent: '{"translate": "block.minecraft.crimson_fence_gate", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_fence_gate"}}}', icon: '"\\u0107"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_fence_gate 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_fence_gate 1", categories: ["fetchr:crimson"]}
## 0108: crimson_nylium
data modify storage fetchr:registries items append value {id: "fetchr:crimson_nylium", item: {id: "minecraft:crimson_nylium"}, textComponent: '{"translate": "block.minecraft.crimson_nylium", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_nylium"}}}', icon: '"\\u0108"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_nylium 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_nylium 1", categories: ["fetchr:crimson"]}
## 0109: crimson_stem
data modify storage fetchr:registries items append value {id: "fetchr:crimson_stem", item: {id: "minecraft:crimson_stem"}, textComponent: '{"translate": "block.minecraft.crimson_stem", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_stem"}}}', icon: '"\\u0109"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_stem 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_stem 1", categories: ["fetchr:crimson"]}
## 010a: crying_obsidian
data modify storage fetchr:registries items append value {id: "fetchr:crying_obsidian", item: {id: "minecraft:crying_obsidian"}, textComponent: '{"translate": "block.minecraft.crying_obsidian", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crying_obsidian"}}}', icon: '"\\u010a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crying_obsidian 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crying_obsidian 1", categories: ["fetchr:obsidian"]}
## 010b: diamond_block
data modify storage fetchr:registries items append value {id: "fetchr:diamond_block", item: {id: "minecraft:diamond_block"}, textComponent: '{"translate": "block.minecraft.diamond_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:diamond_block"}}}', icon: '"\\u010b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:diamond_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:diamond_block 1", categories: ["fetchr:diamond"]}
## 010c: ender_chest
data modify storage fetchr:registries items append value {id: "fetchr:ender_chest", item: {id: "minecraft:ender_chest"}, textComponent: '{"translate": "block.minecraft.ender_chest", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:ender_chest"}}}', icon: '"\\u010c"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:ender_chest 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:ender_chest 1", categories: ["fetchr:treasure"]}
## 010d: gilded_blackstone
data modify storage fetchr:registries items append value {id: "fetchr:gilded_blackstone", item: {id: "minecraft:gilded_blackstone"}, textComponent: '{"translate": "block.minecraft.gilded_blackstone", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:gilded_blackstone"}}}', icon: '"\\u010d"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:gilded_blackstone 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:gilded_blackstone 1", categories: ["fetchr:bastion"]}
## 010e: glowstone
data modify storage fetchr:registries items append value {id: "fetchr:glowstone", item: {id: "minecraft:glowstone"}, textComponent: '{"translate": "block.minecraft.glowstone", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:glowstone"}}}', icon: '"\\u010e"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:glowstone 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:glowstone 1", categories: ["fetchr:light"]}
## 010f: gold_block
data modify storage fetchr:registries items append value {id: "fetchr:gold_block", item: {id: "minecraft:gold_block"}, textComponent: '{"translate": "block.minecraft.gold_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:gold_block"}}}', icon: '"\\u010f"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:gold_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:gold_block 1", categories: ["fetchr:gold"]}
## 0110: gravel
data modify storage fetchr:registries items append value {id: "fetchr:gravel", item: {id: "minecraft:gravel"}, textComponent: '{"translate": "block.minecraft.gravel", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:gravel"}}}', icon: '"\\u0110"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:gravel 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:gravel 1", categories: ["fetchr:flint"]}
## 0111: iron_block
data modify storage fetchr:registries items append value {id: "fetchr:iron_block", item: {id: "minecraft:iron_block"}, textComponent: '{"translate": "block.minecraft.iron_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:iron_block"}}}', icon: '"\\u0111"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:iron_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:iron_block 1", categories: ["fetchr:iron"]}
## 0112: lantern
data modify storage fetchr:registries items append value {id: "fetchr:lantern", item: {id: "minecraft:lantern"}, textComponent: '{"translate": "block.minecraft.lantern", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:lantern"}}}', icon: '"\\u0112"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:lantern 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:lantern 1", categories: ["fetchr:soul_light"]}
## 0113: lodestone
data modify storage fetchr:registries items append value {id: "fetchr:lodestone", item: {id: "minecraft:lodestone"}, textComponent: '{"translate": "block.minecraft.lodestone", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:lodestone"}}}', icon: '"\\u0113"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:lodestone 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:lodestone 1", categories: ["fetchr:treasure"]}
## 0114: magma_block
data modify storage fetchr:registries items append value {id: "fetchr:magma_block", item: {id: "minecraft:magma_block"}, textComponent: '{"translate": "block.minecraft.magma_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:magma_block"}}}', icon: '"\\u0114"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:magma_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:magma_block 1", categories: ["fetchr:basalt"]}
## 0115: nether_bricks
data modify storage fetchr:registries items append value {id: "fetchr:nether_bricks", item: {id: "minecraft:nether_bricks"}, textComponent: '{"translate": "block.minecraft.nether_bricks", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_bricks"}}}', icon: '"\\u0115"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_bricks 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_bricks 1", categories: ["fetchr:fortress"]}
## 0116: nether_gold_ore
data modify storage fetchr:registries items append value {id: "fetchr:nether_gold_ore", item: {id: "minecraft:nether_gold_ore"}, textComponent: '{"translate": "block.minecraft.nether_gold_ore", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_gold_ore"}}}', icon: '"\\u0116"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_gold_ore 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_gold_ore 1", categories: ["fetchr:ore"]}
## 0117: nether_quartz_ore
data modify storage fetchr:registries items append value {id: "fetchr:nether_quartz_ore", item: {id: "minecraft:nether_quartz_ore"}, textComponent: '{"translate": "block.minecraft.nether_quartz_ore", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_quartz_ore"}}}', icon: '"\\u0117"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_quartz_ore 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_quartz_ore 1", categories: ["fetchr:ore"]}
## 0118: nether_wart_block
data modify storage fetchr:registries items append value {id: "fetchr:nether_wart_block", item: {id: "minecraft:nether_wart_block"}, textComponent: '{"translate": "block.minecraft.nether_wart_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_wart_block"}}}', icon: '"\\u0118"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_wart_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_wart_block 1", categories: ["fetchr:nether_wart"]}
## 0119: obsidian
data modify storage fetchr:registries items append value {id: "fetchr:obsidian", item: {id: "minecraft:obsidian"}, textComponent: '{"translate": "block.minecraft.obsidian", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:obsidian"}}}', icon: '"\\u0119"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:obsidian 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:obsidian 1", categories: ["fetchr:obsidian"]}
## 011a: polished_basalt
data modify storage fetchr:registries items append value {id: "fetchr:polished_basalt", item: {id: "minecraft:polished_basalt"}, textComponent: '{"translate": "block.minecraft.polished_basalt", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:polished_basalt"}}}', icon: '"\\u011a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:polished_basalt 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:polished_basalt 1", categories: ["fetchr:basalt"]}
## 011b: quartz_block
data modify storage fetchr:registries items append value {id: "fetchr:quartz_block", item: {id: "minecraft:quartz_block"}, textComponent: '{"translate": "block.minecraft.quartz_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:quartz_block"}}}', icon: '"\\u011b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:quartz_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:quartz_block 1", categories: ["fetchr:quartz"]}
## 011c: quartz_pillar
data modify storage fetchr:registries items append value {id: "fetchr:quartz_pillar", item: {id: "minecraft:quartz_pillar"}, textComponent: '{"translate": "block.minecraft.quartz_pillar", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:quartz_pillar"}}}', icon: '"\\u011c"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:quartz_pillar 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:quartz_pillar 1", categories: ["fetchr:quartz"]}
## 011d: red_nether_bricks
data modify storage fetchr:registries items append value {id: "fetchr:red_nether_bricks", item: {id: "minecraft:red_nether_bricks"}, textComponent: '{"translate": "block.minecraft.red_nether_bricks", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:red_nether_bricks"}}}', icon: '"\\u011d"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:red_nether_bricks 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:red_nether_bricks 1", categories: ["fetchr:fortress"]}
## 011e: respawn_anchor
data modify storage fetchr:registries items append value {id: "fetchr:respawn_anchor", item: {id: "minecraft:respawn_anchor"}, textComponent: '{"translate": "block.minecraft.respawn_anchor", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:respawn_anchor"}}}', icon: '"\\u011e"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:respawn_anchor 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:respawn_anchor 1", categories: ["fetchr:treasure"]}
## 011f: shield
data modify storage fetchr:registries items append value {id: "fetchr:shield", item: {id: "minecraft:shield"}, textComponent: '{"translate": "item.minecraft.shield", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:shield"}}}', icon: '"\\u011f"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:shield 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:shield 1", categories: ["fetchr:misc"]}
## 0120: shroomlight
data modify storage fetchr:registries items append value {id: "fetchr:shroomlight", item: {id: "minecraft:shroomlight"}, textComponent: '{"translate": "block.minecraft.shroomlight", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:shroomlight"}}}', icon: '"\\u0120"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:shroomlight 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:shroomlight 1", categories: ["fetchr:light"]}
## 0121: soul_lantern
data modify storage fetchr:registries items append value {id: "fetchr:soul_lantern", item: {id: "minecraft:soul_lantern"}, textComponent: '{"translate": "block.minecraft.soul_lantern", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:soul_lantern"}}}', icon: '"\\u0121"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:soul_lantern 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:soul_lantern 1", categories: ["fetchr:soul_light"]}
## 0122: soul_sand
data modify storage fetchr:registries items append value {id: "fetchr:soul_sand", item: {id: "minecraft:soul_sand"}, textComponent: '{"translate": "block.minecraft.soul_sand", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:soul_sand"}}}', icon: '"\\u0122"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:soul_sand 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:soul_sand 1", categories: ["fetchr:soul_block"]}
## 0123: soul_soil
data modify storage fetchr:registries items append value {id: "fetchr:soul_soil", item: {id: "minecraft:soul_soil"}, textComponent: '{"translate": "block.minecraft.soul_soil", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:soul_soil"}}}', icon: '"\\u0123"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:soul_soil 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:soul_soil 1", categories: ["fetchr:soul_block"]}
## 0124: soul_torch
data modify storage fetchr:registries items append value {id: "fetchr:soul_torch", item: {id: "minecraft:soul_torch"}, textComponent: '{"translate": "block.minecraft.soul_torch", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:soul_torch"}}}', icon: '"\\u0124"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:soul_torch 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:soul_torch 1", categories: ["fetchr:soul_light"]}
## 0125: twisting_vines
data modify storage fetchr:registries items append value {id: "fetchr:twisting_vines", item: {id: "minecraft:twisting_vines"}, textComponent: '{"translate": "block.minecraft.twisting_vines", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:twisting_vines"}}}', icon: '"\\u0125"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:twisting_vines 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:twisting_vines 1", categories: ["fetchr:warped"]}
## 0126: warped_fence_gate
data modify storage fetchr:registries items append value {id: "fetchr:warped_fence_gate", item: {id: "minecraft:warped_fence_gate"}, textComponent: '{"translate": "block.minecraft.warped_fence_gate", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_fence_gate"}}}', icon: '"\\u0126"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_fence_gate 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_fence_gate 1", categories: ["fetchr:warped"]}
## 0127: warped_nylium
data modify storage fetchr:registries items append value {id: "fetchr:warped_nylium", item: {id: "minecraft:warped_nylium"}, textComponent: '{"translate": "block.minecraft.warped_nylium", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_nylium"}}}', icon: '"\\u0127"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_nylium 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_nylium 1", categories: ["fetchr:warped"]}
## 0128: warped_stem
data modify storage fetchr:registries items append value {id: "fetchr:warped_stem", item: {id: "minecraft:warped_stem"}, textComponent: '{"translate": "block.minecraft.warped_stem", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_stem"}}}', icon: '"\\u0128"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_stem 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_stem 1", categories: ["fetchr:warped"]}
## 0129: warped_wart_block
data modify storage fetchr:registries items append value {id: "fetchr:warped_wart_block", item: {id: "minecraft:warped_wart_block"}, textComponent: '{"translate": "block.minecraft.warped_wart_block", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_wart_block"}}}', icon: '"\\u0129"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_wart_block 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_wart_block 1", categories: ["fetchr:nether_wart"]}
## 012a: weeping_vines
data modify storage fetchr:registries items append value {id: "fetchr:weeping_vines", item: {id: "minecraft:weeping_vines"}, textComponent: '{"translate": "block.minecraft.weeping_vines", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:weeping_vines"}}}', icon: '"\\u012a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:weeping_vines 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:weeping_vines 1", categories: ["fetchr:crimson"]}
## 012b: wither_skeleton_skull
data modify storage fetchr:registries items append value {id: "fetchr:wither_skeleton_skull", item: {id: "minecraft:wither_skeleton_skull"}, textComponent: '{"translate": "block.minecraft.wither_skeleton_skull", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:wither_skeleton_skull"}}}', icon: '"\\u012b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:wither_skeleton_skull 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:wither_skeleton_skull 1", categories: ["fetchr:wither"], weight: 9}
