## 0001: arrow
data modify storage fetchr:registries items append value {id: "fetchr:arrow", item: {id: "minecraft:arrow"}, textComponent: '{"translate": "item.minecraft.arrow", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:arrow"}}}', icon: '"\\u0001"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:arrow 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:arrow 1", categories: ["fetchr:skeleton"]}
## 0002: blaze_rod
data modify storage fetchr:registries items append value {id: "fetchr:blaze_rod", item: {id: "minecraft:blaze_rod"}, textComponent: '{"translate": "item.minecraft.blaze_rod", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:blaze_rod"}}}', icon: '"\\u0002"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:blaze_rod 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:blaze_rod 1", categories: ["fetchr:blaze"]}
## 0003: bone
data modify storage fetchr:registries items append value {id: "fetchr:bone", item: {id: "minecraft:bone"}, textComponent: '{"translate": "item.minecraft.bone", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:bone"}}}', icon: '"\\u0003"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:bone 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:bone 1", categories: ["fetchr:skeleton"]}
## 0004: brewing_stand
data modify storage fetchr:registries items append value {id: "fetchr:brewing_stand", item: {id: "minecraft:brewing_stand"}, textComponent: '{"translate": "item.minecraft.brewing_stand", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:brewing_stand"}}}', icon: '"\\u0004"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:brewing_stand 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:brewing_stand 1", categories: ["fetchr:potion", "fetchr:fortress"]}
## 0005: brown_mushroom
data modify storage fetchr:registries items append value {id: "fetchr:brown_mushroom", item: {id: "minecraft:brown_mushroom"}, textComponent: '{"translate": "block.minecraft.brown_mushroom", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:brown_mushroom"}}}', icon: '"\\u0005"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:brown_mushroom 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:brown_mushroom 1", categories: ["fetchr:mushroom"]}
## 0006: chain
data modify storage fetchr:registries items append value {id: "fetchr:chain", item: {id: "minecraft:chain"}, textComponent: '{"translate": "block.minecraft.chain", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:chain"}}}', icon: '"\\u0006"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:chain 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:chain 1", categories: ["fetchr:iron"]}
## 0007: cooked_porkchop
data modify storage fetchr:registries items append value {id: "fetchr:cooked_porkchop", item: {id: "minecraft:cooked_porkchop"}, textComponent: '{"translate": "item.minecraft.cooked_porkchop", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:cooked_porkchop"}}}', icon: '"\\u0007"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:cooked_porkchop 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:cooked_porkchop 1", categories: ["fetchr:hoglin"]}
## 0008: crimson_fungus
data modify storage fetchr:registries items append value {id: "fetchr:crimson_fungus", item: {id: "minecraft:crimson_fungus"}, textComponent: '{"translate": "block.minecraft.crimson_fungus", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_fungus"}}}', icon: '"\\u0008"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_fungus 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_fungus 1", categories: ["fetchr:crimson"]}
## 0009: crimson_hanging_sign
data modify storage fetchr:registries items append value {id: "fetchr:crimson_hanging_sign", item: {id: "minecraft:crimson_hanging_sign"}, textComponent: '{"translate": "block.minecraft.crimson_hanging_sign", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_hanging_sign"}}}', icon: '"\\u0009"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_hanging_sign 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_hanging_sign 1", categories: ["fetchr:crimson"]}
## 000a: crimson_roots
data modify storage fetchr:registries items append value {id: "fetchr:crimson_roots", item: {id: "minecraft:crimson_roots"}, textComponent: '{"translate": "block.minecraft.crimson_roots", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_roots"}}}', icon: '"\\u000a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_roots 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_roots 1", categories: ["fetchr:crimson"]}
## 000b: crimson_sign
data modify storage fetchr:registries items append value {id: "fetchr:crimson_sign", item: {id: "minecraft:crimson_sign"}, textComponent: '{"translate": "block.minecraft.crimson_sign", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crimson_sign"}}}', icon: '"\\u000b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crimson_sign 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crimson_sign 1", categories: ["fetchr:crimson"]}
## 000c: crossbow
data modify storage fetchr:registries items append value {id: "fetchr:crossbow", item: {id: "minecraft:crossbow"}, textComponent: '{"translate": "item.minecraft.crossbow", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:crossbow"}}}', icon: '"\\u000c"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:crossbow 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:crossbow 1", categories: ["fetchr:misc"]}
## 000d: diamond
data modify storage fetchr:registries items append value {id: "fetchr:diamond", item: {id: "minecraft:diamond"}, textComponent: '{"translate": "item.minecraft.diamond", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:diamond"}}}', icon: '"\\u000d"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:diamond 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:diamond 1", categories: ["fetchr:diamond"]}
## 000e: diamond_axe
data modify storage fetchr:registries items append value {id: "fetchr:diamond_axe", item: {id: "minecraft:diamond_axe"}, textComponent: '{"translate": "item.minecraft.diamond_axe", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:diamond_axe"}}}', icon: '"\\u000e"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:diamond_axe 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:diamond_axe 1", categories: ["fetchr:diamond_tool"]}
## 000f: diamond_shovel
data modify storage fetchr:registries items append value {id: "fetchr:diamond_shovel", item: {id: "minecraft:diamond_shovel"}, textComponent: '{"translate": "item.minecraft.diamond_shovel", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:diamond_shovel"}}}', icon: '"\\u000f"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:diamond_shovel 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:diamond_shovel 1", categories: ["fetchr:diamond_tool"]}
## 0010: enchanted_book
data modify storage fetchr:registries items append value {id: "fetchr:enchanted_book", item: {id: "minecraft:enchanted_book"}, textComponent: '{"translate": "item.minecraft.enchanted_book", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:enchanted_book"}}}', icon: '"\\u0010"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:enchanted_book 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:enchanted_book 1", categories: ["fetchr:treasure"]}
## 0011: ender_eye
data modify storage fetchr:registries items append value {id: "fetchr:ender_eye", item: {id: "minecraft:ender_eye"}, textComponent: '{"translate": "item.minecraft.ender_eye", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:ender_eye"}}}', icon: '"\\u0011"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:ender_eye 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:ender_eye 1", categories: ["fetchr:enderman"]}
## 0012: ender_pearl
data modify storage fetchr:registries items append value {id: "fetchr:ender_pearl", item: {id: "minecraft:ender_pearl"}, textComponent: '{"translate": "item.minecraft.ender_pearl", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:ender_pearl"}}}', icon: '"\\u0012"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:ender_pearl 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:ender_pearl 1", categories: ["fetchr:enderman"]}
## 0013: fire_charge
data modify storage fetchr:registries items append value {id: "fetchr:fire_charge", item: {id: "minecraft:fire_charge"}, textComponent: '{"translate": "item.minecraft.fire_charge", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:fire_charge"}}}', icon: '"\\u0013"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:fire_charge 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:fire_charge 1", categories: ["fetchr:piglin"]}
## 0014: flint_and_steel
data modify storage fetchr:registries items append value {id: "fetchr:flint_and_steel", item: {id: "minecraft:flint_and_steel"}, textComponent: '{"translate": "item.minecraft.flint_and_steel", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:flint_and_steel"}}}', icon: '"\\u0014"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:flint_and_steel 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:flint_and_steel 1", categories: ["fetchr:flint"]}
## 0015: ghast_tear
data modify storage fetchr:registries items append value {id: "fetchr:ghast_tear", item: {id: "minecraft:ghast_tear"}, textComponent: '{"translate": "item.minecraft.ghast_tear", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:ghast_tear"}}}', icon: '"\\u0015"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:ghast_tear 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:ghast_tear 1", categories: ["fetchr:ghast"]}
## 0016: glass_bottle
data modify storage fetchr:registries items append value {id: "fetchr:glass_bottle", item: {id: "minecraft:glass_bottle"}, textComponent: '{"translate": "item.minecraft.glass_bottle", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:glass_bottle"}}}', icon: '"\\u0016"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:glass_bottle 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:glass_bottle 1", categories: ["fetchr:potion"]}
## 0017: gold_ingot
data modify storage fetchr:registries items append value {id: "fetchr:gold_ingot", item: {id: "minecraft:gold_ingot"}, textComponent: '{"translate": "item.minecraft.gold_ingot", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:gold_ingot"}}}', icon: '"\\u0017"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:gold_ingot 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:gold_ingot 1", categories: ["fetchr:gold"]}
## 0018: gold_nugget
data modify storage fetchr:registries items append value {id: "fetchr:gold_nugget", item: {id: "minecraft:gold_nugget"}, textComponent: '{"translate": "item.minecraft.gold_nugget", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:gold_nugget"}}}', icon: '"\\u0018"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:gold_nugget 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:gold_nugget 1", categories: ["fetchr:gold"]}
## 0019: golden_apple
data modify storage fetchr:registries items append value {id: "fetchr:golden_apple", item: {id: "minecraft:golden_apple"}, textComponent: '{"translate": "item.minecraft.golden_apple", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_apple"}}}', icon: '"\\u0019"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_apple 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_apple 1", categories: ["fetchr:treasure"]}
## 001a: golden_axe
data modify storage fetchr:registries items append value {id: "fetchr:golden_axe", item: {id: "minecraft:golden_axe"}, textComponent: '{"translate": "item.minecraft.golden_axe", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_axe"}}}', icon: '"\\u001a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_axe 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_axe 1", categories: ["fetchr:golden_tool"]}
## 001b: golden_boots
data modify storage fetchr:registries items append value {id: "fetchr:golden_boots", item: {id: "minecraft:golden_boots"}, textComponent: '{"translate": "item.minecraft.golden_boots", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_boots"}}}', icon: '"\\u001b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_boots 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_boots 1", categories: ["fetchr:golden_armor"]}
## 001c: golden_chestplate
data modify storage fetchr:registries items append value {id: "fetchr:golden_chestplate", item: {id: "minecraft:golden_chestplate"}, textComponent: '{"translate": "item.minecraft.golden_chestplate", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_chestplate"}}}', icon: '"\\u001c"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_chestplate 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_chestplate 1", categories: ["fetchr:golden_armor"]}
## 001d: golden_helmet
data modify storage fetchr:registries items append value {id: "fetchr:golden_helmet", item: {id: "minecraft:golden_helmet"}, textComponent: '{"translate": "item.minecraft.golden_helmet", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_helmet"}}}', icon: '"\\u001d"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_helmet 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_helmet 1", categories: ["fetchr:golden_armor"]}
## 001e: golden_horse_armor
data modify storage fetchr:registries items append value {id: "fetchr:golden_horse_armor", item: {id: "minecraft:golden_horse_armor"}, textComponent: '{"translate": "item.minecraft.golden_horse_armor", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_horse_armor"}}}', icon: '"\\u001e"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_horse_armor 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_horse_armor 1", categories: ["fetchr:treasure"]}
## 001f: golden_leggings
data modify storage fetchr:registries items append value {id: "fetchr:golden_leggings", item: {id: "minecraft:golden_leggings"}, textComponent: '{"translate": "item.minecraft.golden_leggings", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_leggings"}}}', icon: '"\\u001f"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_leggings 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_leggings 1", categories: ["fetchr:golden_armor"]}
## 0020: golden_shovel
data modify storage fetchr:registries items append value {id: "fetchr:golden_shovel", item: {id: "minecraft:golden_shovel"}, textComponent: '{"translate": "item.minecraft.golden_shovel", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:golden_shovel"}}}', icon: '"\\u0020"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:golden_shovel 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:golden_shovel 1", categories: ["fetchr:golden_tool"]}
## 0021: iron_ingot
data modify storage fetchr:registries items append value {id: "fetchr:iron_ingot", item: {id: "minecraft:iron_ingot"}, textComponent: '{"translate": "item.minecraft.iron_ingot", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:iron_ingot"}}}', icon: '"\\u0021"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:iron_ingot 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:iron_ingot 1", categories: ["fetchr:iron"]}
## 0022: iron_nugget
data modify storage fetchr:registries items append value {id: "fetchr:iron_nugget", item: {id: "minecraft:iron_nugget"}, textComponent: '{"translate": "item.minecraft.iron_nugget", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:iron_nugget"}}}', icon: '"\\u0022"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:iron_nugget 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:iron_nugget 1", categories: ["fetchr:iron"]}
## 0023: lava_bucket
data modify storage fetchr:registries items append value {id: "fetchr:lava_bucket", item: {id: "minecraft:lava_bucket"}, textComponent: '{"translate": "item.minecraft.lava_bucket", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:lava_bucket"}}}', icon: '"\\u0023"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:lava_bucket 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:lava_bucket 1", categories: ["fetchr:misc"]}
## 0024: leather
data modify storage fetchr:registries items append value {id: "fetchr:leather", item: {id: "minecraft:leather"}, textComponent: '{"translate": "item.minecraft.leather", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:leather"}}}', icon: '"\\u0024"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:leather 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:leather 1", categories: ["fetchr:hoglin"]}
## 0025: magma_cream
data modify storage fetchr:registries items append value {id: "fetchr:magma_cream", item: {id: "minecraft:magma_cream"}, textComponent: '{"translate": "item.minecraft.magma_cream", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:magma_cream"}}}', icon: '"\\u0025"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:magma_cream 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:magma_cream 1", categories: ["fetchr:magma_cream"]}
## 0026: nether_brick
data modify storage fetchr:registries items append value {id: "fetchr:nether_brick", item: {id: "minecraft:nether_brick"}, textComponent: '{"translate": "item.minecraft.nether_brick", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_brick"}}}', icon: '"\\u0026"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_brick 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_brick 1", categories: ["fetchr:fortress"]}
## 0027: nether_star
data modify storage fetchr:registries items append value {id: "fetchr:nether_star", item: {id: "minecraft:nether_star"}, textComponent: '{"translate": "item.minecraft.nether_star", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_star"}}}', icon: '"\\u0027"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_star 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_star 1", categories: ["fetchr:wither"], weight: 1}
## 0028: nether_wart
data modify storage fetchr:registries items append value {id: "fetchr:nether_wart", item: {id: "minecraft:nether_wart"}, textComponent: '{"translate": "item.minecraft.nether_wart", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:nether_wart"}}}', icon: '"\\u0028"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:nether_wart 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:nether_wart 1", categories: ["fetchr:nether_wart"]}
## 0029: netherite_axe
data modify storage fetchr:registries items append value {id: "fetchr:netherite_axe", item: {id: "minecraft:netherite_axe"}, textComponent: '{"translate": "item.minecraft.netherite_axe", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:netherite_axe"}}}', icon: '"\\u0029"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:netherite_axe 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:netherite_axe 1", categories: ["fetchr:netherite"]}
## 002a: netherite_ingot
data modify storage fetchr:registries items append value {id: "fetchr:netherite_ingot", item: {id: "minecraft:netherite_ingot"}, textComponent: '{"translate": "item.minecraft.netherite_ingot", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:netherite_ingot"}}}', icon: '"\\u002a"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:netherite_ingot 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:netherite_ingot 1", categories: ["fetchr:netherite"]}
## 002b: netherite_scrap
data modify storage fetchr:registries items append value {id: "fetchr:netherite_scrap", item: {id: "minecraft:netherite_scrap"}, textComponent: '{"translate": "item.minecraft.netherite_scrap", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:netherite_scrap"}}}', icon: '"\\u002b"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:netherite_scrap 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:netherite_scrap 1", categories: ["fetchr:netherite"]}
## 002c: netherite_shovel
data modify storage fetchr:registries items append value {id: "fetchr:netherite_shovel", item: {id: "minecraft:netherite_shovel"}, textComponent: '{"translate": "item.minecraft.netherite_shovel", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:netherite_shovel"}}}', icon: '"\\u002c"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:netherite_shovel 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:netherite_shovel 1", categories: ["fetchr:netherite"]}
## 002d: netherite_upgrade_smithing_template
data modify storage fetchr:registries items append value {id: "fetchr:netherite_upgrade_smithing_template", item: {id: "minecraft:netherite_upgrade_smithing_template"}, textComponent: '{"translate": "item.minecraft.netherite_upgrade_smithing_template", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:netherite_upgrade_smithing_template"}}}', icon: '"\\u002d"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:netherite_upgrade_smithing_template 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:netherite_upgrade_smithing_template 1", categories: ["fetchr:netherite"]}
## 002e: porkchop
data modify storage fetchr:registries items append value {id: "fetchr:porkchop", item: {id: "minecraft:porkchop"}, textComponent: '{"translate": "item.minecraft.porkchop", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:porkchop"}}}', icon: '"\\u002e"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:porkchop 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:porkchop 1", categories: ["fetchr:hoglin"]}
## 002f: quartz
data modify storage fetchr:registries items append value {id: "fetchr:quartz", item: {id: "minecraft:quartz"}, textComponent: '{"translate": "item.minecraft.quartz", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:quartz"}}}', icon: '"\\u002f"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:quartz 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:quartz 1", categories: ["fetchr:quartz"]}
## 0030: red_mushroom
data modify storage fetchr:registries items append value {id: "fetchr:red_mushroom", item: {id: "minecraft:red_mushroom"}, textComponent: '{"translate": "block.minecraft.red_mushroom", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:red_mushroom"}}}', icon: '"\\u0030"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:red_mushroom 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:red_mushroom 1", categories: ["fetchr:mushroom"]}
## 0031: shears
data modify storage fetchr:registries items append value {id: "fetchr:shears", item: {id: "minecraft:shears"}, textComponent: '{"translate": "item.minecraft.shears", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:shears"}}}', icon: '"\\u0031"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:shears 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:shears 1", categories: ["fetchr:misc"]}
## 0032: soul_campfire
data modify storage fetchr:registries items append value {id: "fetchr:soul_campfire", item: {id: "minecraft:soul_campfire"}, textComponent: '{"translate": "block.minecraft.soul_campfire", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:soul_campfire"}}}', icon: '"\\u0032"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:soul_campfire 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:soul_campfire 1", categories: ["fetchr:soul_light"]}
## 0033: spectral_arrow
data modify storage fetchr:registries items append value {id: "fetchr:spectral_arrow", item: {id: "minecraft:spectral_arrow"}, textComponent: '{"translate": "item.minecraft.spectral_arrow", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:spectral_arrow"}}}', icon: '"\\u0033"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:spectral_arrow 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:spectral_arrow 1", categories: ["fetchr:piglin"]}
## 0034: string
data modify storage fetchr:registries items append value {id: "fetchr:string", item: {id: "minecraft:string"}, textComponent: '{"translate": "item.minecraft.string", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:string"}}}', icon: '"\\u0034"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:string 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:string 1", categories: ["fetchr:piglin"]}
## 0035: warped_fungus
data modify storage fetchr:registries items append value {id: "fetchr:warped_fungus", item: {id: "minecraft:warped_fungus"}, textComponent: '{"translate": "block.minecraft.warped_fungus", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_fungus"}}}', icon: '"\\u0035"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_fungus 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_fungus 1", categories: ["fetchr:warped"]}
## 0036: warped_hanging_sign
data modify storage fetchr:registries items append value {id: "fetchr:warped_hanging_sign", item: {id: "minecraft:warped_hanging_sign"}, textComponent: '{"translate": "block.minecraft.warped_hanging_sign", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_hanging_sign"}}}', icon: '"\\u0036"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_hanging_sign 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_hanging_sign 1", categories: ["fetchr:warped"]}
## 0037: warped_roots
data modify storage fetchr:registries items append value {id: "fetchr:warped_roots", item: {id: "minecraft:warped_roots"}, textComponent: '{"translate": "block.minecraft.warped_roots", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_roots"}}}', icon: '"\\u0037"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_roots 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_roots 1", categories: ["fetchr:warped"]}
## 0038: warped_sign
data modify storage fetchr:registries items append value {id: "fetchr:warped_sign", item: {id: "minecraft:warped_sign"}, textComponent: '{"translate": "block.minecraft.warped_sign", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:warped_sign"}}}', icon: '"\\u0038"', detectCommand: "execute as @a[tag=fetchr.check_slot] store success score @s fetchr.has_item run clear @s minecraft:warped_sign 0", clearCommand: "clear @a[tag=fetchr.clear] minecraft:warped_sign 1", categories: ["fetchr:warped"]}
